mardown: kramdown
kramdown:
    input: GFM
port: 8080
sass:
    sass_dir: assets/styles
    no-cache:
    style: nested
exclude: ['/ignore']
stylesheet_root: /assets/styles/
main_stylesheet: style.css