port: 8080
exclude: ['/ignore', 'jmariner.com.sublime-*']

plugins: [jekyll-tidy]
mardown: kramdown
kramdown:
    input: GFM
sass:
  sass_dir: _scss
  style: expanded

environment: development

name: jmariner.com
bootswatch: paper
md_footer: footer.md
# site_dir: ~/html/root